-- ==============================================================================
-- Employee Management System (EMS) - Presentation MVP Database Schema
-- Target Database: PostgreSQL / Supabase
-- Script Version: 1.0.0
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. USERS TABLE
-- Stores authentication, role, and account status for all system users.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    official_email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'EMPLOYEE')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ------------------------------------------------------------------------------
-- 2. DEPARTMENTS TABLE
-- Represents organizational departments/units within the company.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_departments_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ------------------------------------------------------------------------------
-- 3. EMPLOYEES TABLE
-- Stores primary professional employment records linked 1-to-1 with users.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    department_id BIGINT NOT NULL,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    joining_date DATE NOT NULL,
    profile_photo TEXT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_employees_department FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE RESTRICT,
    CONSTRAINT chk_employees_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ------------------------------------------------------------------------------
-- 4. EMPLOYEE_PERSONAL_INFO TABLE
-- Stores secondary personal and emergency contact information (1-to-1 with employees).
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employee_personal_info (
    employee_id BIGINT PRIMARY KEY,
    personal_phone VARCHAR(50) NULL,
    personal_email VARCHAR(255) NULL,
    address TEXT NULL,
    emergency_contact_name VARCHAR(255) NULL,
    emergency_contact_number VARCHAR(50) NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_personal_info_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE CASCADE
);

-- ------------------------------------------------------------------------------
-- 5. DOCUMENTS TABLE
-- Metadata and verification tracking for employee uploaded documents.
-- NOTE: Binary files are stored in external storage (e.g. Supabase Storage),
--       only the metadata reference is stored in this table.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    document_title VARCHAR(255) NOT NULL,
    file_reference TEXT NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL,
    rejection_reason TEXT NULL,
    reviewed_by BIGINT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP NULL,
    CONSTRAINT fk_documents_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE RESTRICT,
    CONSTRAINT fk_documents_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT chk_documents_type CHECK (document_type IN (
        'EDUCATIONAL_CERTIFICATE',
        'PROFESSIONAL_CERTIFICATE',
        'IDENTITY_DOCUMENT',
        'PREVIOUS_EXPERIENCE',
        'OTHER'
    )),
    CONSTRAINT chk_documents_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- ------------------------------------------------------------------------------
-- 6. AUDIT_LOGS TABLE
-- Tracks security events, administrative changes, and module activities.
-- Preserved even if initiating user account is deleted (user_id SET NULL).
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    action VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    record_id BIGINT NULL,
    change_details TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

-- ------------------------------------------------------------------------------
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- ------------------------------------------------------------------------------
-- Department and status filtering on employees
CREATE INDEX IF NOT EXISTS idx_employees_department_id ON employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_status ON employees(status);
CREATE INDEX IF NOT EXISTS idx_employees_employee_code ON employees(employee_code);

-- Document lookups by employee and review status
CREATE INDEX IF NOT EXISTS idx_documents_employee_id ON documents(employee_id);
CREATE INDEX IF NOT EXISTS idx_documents_status ON documents(status);
CREATE INDEX IF NOT EXISTS idx_documents_employee_status ON documents(employee_id, status);

-- Audit log query acceleration
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_module_record ON audit_logs(module, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
