package com.ems.ui;
import com.ems.model.*;import com.ems.service.DocumentService;import com.ems.session.SessionManager;import com.ems.ui.components.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.io.File;import java.util.*;
public class DocumentApprovals extends JFrame{
 private final User user=SessionManager.getInstance().getCurrentUser();private final DocumentService service=new DocumentService();private final DefaultTableModel model=new DefaultTableModel(new Object[]{"ID","Employee","Title","Type","Uploaded","Status"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(model);
 public DocumentApprovals(){if(user==null||!SessionManager.getInstance().isLoggedIn()||!user.isAdmin())throw new IllegalStateException("Administrator session required.");initUI();load();}
 private void initUI(){setTitle("Document Approvals - Employee Management System");setSize(1050,680);setLocationRelativeTo(null);setDefaultCloseOperation(DISPOSE_ON_CLOSE);JPanel root=new JPanel(new BorderLayout());root.setBackground(UIConstants.COLOR_BACKGROUND);root.add(new SidebarPanel(user,Arrays.asList("Dashboard","Employees","Document Approvals","Logout"),"Document Approvals",this::logout,this::nav),BorderLayout.WEST);
  JPanel main=new JPanel(new BorderLayout());main.setBackground(UIConstants.COLOR_BACKGROUND);JPanel h=new JPanel(new BorderLayout());h.setBackground(Color.WHITE);h.setBorder(BorderFactory.createEmptyBorder(20,26,20,26));JLabel t=new JLabel("Document Approvals");t.setFont(UIConstants.FONT_TITLE);h.add(t,BorderLayout.WEST);JButton refresh=new JButton("Refresh");refresh.addActionListener(e->load());h.add(refresh,BorderLayout.EAST);main.add(h,BorderLayout.NORTH);
  JPanel c=new JPanel(new BorderLayout(0,10));c.setBorder(BorderFactory.createEmptyBorder(24,26,26,26));c.setBackground(UIConstants.COLOR_BACKGROUND);table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);table.setRowHeight(34);c.add(new JScrollPane(table),BorderLayout.CENTER);JPanel a=new JPanel(new FlowLayout(FlowLayout.RIGHT));JButton view=new JButton("View"),approve=new JButton("Approve"),reject=new JButton("Reject");a.add(view);a.add(approve);a.add(reject);view.addActionListener(e->view());approve.addActionListener(e->approve());reject.addActionListener(e->reject());c.add(a,BorderLayout.SOUTH);main.add(c,BorderLayout.CENTER);root.add(main,BorderLayout.CENTER);setContentPane(root);}
 private Document selected(){int r=table.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Select a document first.");return null;}return service.getDocument(Long.parseLong(model.getValueAt(r,0).toString()));}
 private void load(){try{model.setRowCount(0);for(Document d:service.getPendingDocuments())model.addRow(new Object[]{d.getDocumentId(),d.getEmployeeId(),d.getDocumentTitle(),d.getDocumentType().replace('_',' '),d.getUploadedAt(),d.getStatus()});}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);}}
 private void view(){Document d=selected();if(d==null)return;File f=new File(d.getFileReference());if(!f.exists()){JOptionPane.showMessageDialog(this,"File not found: "+d.getFileReference());return;}try{Desktop.getDesktop().open(f);}catch(Exception e){JOptionPane.showMessageDialog(this,"Unable to open file.");}}
 private void approve(){Document d=selected();if(d==null)return;if(JOptionPane.showConfirmDialog(this,"Approve "+d.getDocumentTitle()+"?","Confirm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;try{service.approve(d.getDocumentId());JOptionPane.showMessageDialog(this,"Document approved.");load();}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
 private void reject(){Document d=selected();if(d==null)return;String reason=JOptionPane.showInputDialog(this,"Rejection reason:");if(reason==null)return;try{service.reject(d.getDocumentId(),reason);JOptionPane.showMessageDialog(this,"Document rejected.");load();}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
 private void nav(String x){if("Dashboard".equalsIgnoreCase(x)){dispose();new AdminDashboard(user).setVisible(true);}else if("Employees".equalsIgnoreCase(x))new EmployeeManagement().setVisible(true);}private void logout(){SessionManager.getInstance().logout();dispose();new LoginScreen().setVisible(true);}
}