package com.ems.ui;
import com.ems.model.*;import com.ems.service.DocumentService;import com.ems.session.SessionManager;import com.ems.ui.components.*;import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.util.*;
public class MyDocuments extends JFrame{
 private final User user=SessionManager.getInstance().getCurrentUser();private final DocumentService service=new DocumentService();private final DefaultTableModel model=new DefaultTableModel(new Object[]{"Title","Type","Status","Uploaded","Rejection Reason"},0){public boolean isCellEditable(int r,int c){return false;}};private JLabel summary;
 public MyDocuments(){if(user==null||!SessionManager.getInstance().isLoggedIn()||!"EMPLOYEE".equalsIgnoreCase(user.getRole()))throw new IllegalStateException("Employee session required.");initUI();load();}
 private void initUI(){setTitle("My Documents - Employee Management System");setSize(1050,680);setLocationRelativeTo(null);setDefaultCloseOperation(DISPOSE_ON_CLOSE);JPanel root=new JPanel(new BorderLayout());root.setBackground(UIConstants.COLOR_BACKGROUND);root.add(new SidebarPanel(user,Arrays.asList("Dashboard","My Documents","Logout"),"My Documents",this::logout,this::nav),BorderLayout.WEST);
  JPanel main=new JPanel(new BorderLayout());main.setBackground(UIConstants.COLOR_BACKGROUND);JPanel head=new JPanel(new BorderLayout());head.setBackground(Color.WHITE);head.setBorder(BorderFactory.createEmptyBorder(20,26,20,26));JLabel t=new JLabel("My Documents");t.setFont(UIConstants.FONT_TITLE);head.add(t,BorderLayout.WEST);JButton up=new JButton("+ Upload Document");up.addActionListener(e->new UploadDocumentDialog(this,this::load).setVisible(true));head.add(up,BorderLayout.EAST);
  JPanel content=new JPanel(new BorderLayout(0,12));content.setBorder(BorderFactory.createEmptyBorder(24,26,26,26));content.setBackground(UIConstants.COLOR_BACKGROUND);summary=new JLabel("Loading...");content.add(summary,BorderLayout.NORTH);JTable table=new JTable(model);table.setRowHeight(34);content.add(new JScrollPane(table),BorderLayout.CENTER);main.add(head,BorderLayout.NORTH);main.add(content,BorderLayout.CENTER);root.add(main,BorderLayout.CENTER);setContentPane(root);}
 private void load(){try{List<Document> ds=service.getCurrentEmployeeDocuments();model.setRowCount(0);int p=0,a=0,r=0;for(Document d:ds){if("PENDING".equals(d.getStatus()))p++;if("APPROVED".equals(d.getStatus()))a++;if("REJECTED".equals(d.getStatus()))r++;model.addRow(new Object[]{d.getDocumentTitle(),d.getDocumentType().replace('_',' '),d.getStatus(),d.getUploadedAt(),d.getRejectionReason()==null?"":d.getRejectionReason()});}summary.setText("Total: "+ds.size()+" | Pending: "+p+" | Approved: "+a+" | Rejected: "+r);}catch(Exception e){summary.setText("Unable to load documents: "+e.getMessage());}}
 private void nav(String x){if("Dashboard".equalsIgnoreCase(x)){dispose();new EmployeeDashboard(user).setVisible(true);}}private void logout(){SessionManager.getInstance().logout();dispose();new LoginScreen().setVisible(true);}
}